### ISSUE TITLE
HTML Headings dont appear to work

### ISSUE THREAD

**Issue by bstuhlsa** [gwintzer/kibana-html-plugin#17]
The below yields the same font size.  Some things do work like bold, italics, tables.
```
<h1>Heading 1</h1>
<h2>Heading 2</h2>
<h3>Heading 3</h3>
<h4>Heading 4</h4>
<h5>Heading 5</h5>
<h6>Heading 6</h6>

**Comment by gwintzer** [comment]
Look at the screenshot, you will see an example of working header.

According to the EUI (https://elastic.github.io/eui/#/) stylesheets, you have to append an extra classnames `euiTitle euiTitle-large` to apply headers style

**Comment by bstuhlsa** [comment]
Thank you very much, this works.  I was using work arounds like:  "<p style="font-size:30px">Sample Text</p>"

The documentation specifically at:  https://elastic.github.io/eui/#/guidelines/text-scales, was beneficial.
